lib/plan_picker_web/router.ex
defmodule PlanPickerWeb.Router do
  use PlanPickerWeb, :router

  import PlanPickerWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug :put_root_layout, {PlanPickerWeb.LayoutView, :root}
  end

  pipeline :require_authenticated_user_having_data do
    plug :require_authenticated_user
    plug :put_roles_if_authenticated
  end

  pipeline :require_moderator_role do
    plug :require_authenticated_user_having_data
    plug :require_role, :moderator
  end

  pipeline :require_admin_role do
    plug :require_authenticated_user_having_data
    plug :require_role, :admin
  end

  scope "/", PlanPickerWeb do
    pipe_through [:browser, :put_roles_if_authenticated]

    get "/", PageController, :index
  end

  # Enables LiveDashboard only for development
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: PlanPickerWeb.Telemetry, ecto_repos: [PlanPicker.Repo]
    end
  end

  ## Authentication routes
  scope "/", PlanPickerWeb.Accounts do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  ## Session management routes
  scope "/", PlanPickerWeb.Accounts do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end

  ## User settings routes
  scope "/", PlanPickerWeb.Accounts do
    pipe_through [:browser, :require_authenticated_user_having_data]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", PlanPickerWeb do
    pipe_through [:browser, :require_authenticated_user_having_data]
    live "/enrollments/:id/show", EnrollmentLive, :show
  end

  # moderator or admin routes
  scope "/manage/", PlanPickerWeb do
    pipe_through [:browser, :require_moderator_role]

    get "/enrollments/", EnrollmentManagementController, :index
    get "/enrollments/:id/show", EnrollmentManagementController, :show
    live "/enrollments/:id/edit", EnrollmentManagementLive, :edit

    live "/enrollments/:id/classes", ClassManagementLive
  end

  # admin only routes
  scope "/manage/", PlanPickerWeb do
    pipe_through [:browser, :require_admin_role]

    get "/enrollments/new", EnrollmentManagementController, :new
    post "/enrollments/", EnrollmentManagementController, :create
    delete "/enrollments/:id", EnrollmentManagementController, :delete

    get "/users/", UserController, :index
  end
end

lib/plan_picker_web/views/layout_view.ex
defmodule PlanPickerWeb.LayoutView do
  use PlanPickerWeb, :view
end

lib/plan_picker_web/templates/layout/_navbar.html.eex
<section>
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand mx-6">
      <%= link to: Routes.page_path(@conn, :index), class: "navbar-item" do %>
        <img src="<%= Routes.static_path(@conn, "/favicon.svg") %>" class="logo">
      <% end %>

      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div class="navbar-end">
      <div class="navbar-item is-flex-direction-column">
<%= if authenticated?(@conn) do %>
  <%= render "_navbar_logged_in.html", assigns %>
<% else %>
  <%= render "_navbar_logged_out.html", assigns %>
<% end %>
      </div>
    </div>
  </nav>
</section>

lib/plan_picker_web/templates/layout/_navbar_logged_in.html.eex
 <div class="column">
  <div class="column">
    <span class="is-size-6"><%= current_user(@conn).email %></span>
<%= if :moderator in @roles do %>
    <span class="tag is-primary">Moderator</span>
<% end %>
<%= if :admin in @roles do %>
    <span class="tag is-primary">Admin</span>
<% end %>
  </div>
  <div class="buttons">
    <%= link "Settings", to: Routes.user_settings_path(@conn, :edit), class: "button is-light" %>
    <%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete, class: "button is-light" %>
</div>

lib/plan_picker_web/templates/layout/_navbar_logged_out.html.eex
<div class="buttons">
  <%= link to: Routes.user_registration_path(@conn, :new), class: "button is-primary" do %><strong>Register</strong><% end %>
  <%= link "Log in", to: Routes.user_session_path(@conn, :new), class: "button is-light" %>
</div>

lib/plan_picker_web/templates/layout/app.html.eex
<p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
<p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
<%= @inner_content %>

lib/plan_picker_web/templates/layout/live.html.leex
<p class="alert alert-info" role="alert"><%= live_flash(@flash, :info) %></p>
<p class="alert alert-danger" role="alert"><%= live_flash(@flash, :error) %></p>
<%= @inner_content %>

lib/plan_picker_web/templates/layout/root.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Plan picker</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="icon" href="<%= Routes.static_path(@conn, "/favicon.svg") %>" />
    <%= csrf_meta_tag() %>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <%= render "_navbar.html", assigns %>
    </header>
    <main role="main" class="container">
      <%= @inner_content %>
    </main>
  </body>
</html>