lib/plan_picker_web/router.ex
defmodule PlanPickerWeb.Router do
  use PlanPickerWeb, :router

  import PlanPickerWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug :put_root_layout, {PlanPickerWeb.LayoutView, :root}
  end

  pipeline :require_authenticated_user_having_data do
    plug :require_authenticated_user
    plug :put_roles_if_authenticated
  end

  pipeline :require_moderator_role do
    plug :require_authenticated_user_having_data
    plug :require_role, :moderator
  end

  pipeline :require_admin_role do
    plug :require_authenticated_user_having_data
    plug :require_role, :admin
  end

  scope "/", PlanPickerWeb do
    pipe_through [:browser, :put_roles_if_authenticated]

    get "/", PageController, :index
  end

  # Enables LiveDashboard only for development
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: PlanPickerWeb.Telemetry, ecto_repos: [PlanPicker.Repo]
    end
  end

  ## Authentication routes
  scope "/", PlanPickerWeb.Accounts do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  ## Session management routes
  scope "/", PlanPickerWeb.Accounts do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end

  ## User settings routes
  scope "/", PlanPickerWeb.Accounts do
    pipe_through [:browser, :require_authenticated_user_having_data]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", PlanPickerWeb do
    pipe_through [:browser, :require_authenticated_user_having_data]
    live "/enrollments/:id/show", EnrollmentLive, :show
  end

  # moderator or admin routes
  scope "/manage/", PlanPickerWeb do
    pipe_through [:browser, :require_moderator_role]

    get "/enrollments/", EnrollmentManagementController, :index
    get "/enrollments/:id/show", EnrollmentManagementController, :show
    live "/enrollments/:id/edit", EnrollmentManagementLive, :edit

    live "/enrollments/:id/classes", ClassManagementLive
  end

  # admin only routes
  scope "/manage/", PlanPickerWeb do
    pipe_through [:browser, :require_admin_role]

    get "/enrollments/new", EnrollmentManagementController, :new
    post "/enrollments/", EnrollmentManagementController, :create
    delete "/enrollments/:id", EnrollmentManagementController, :delete

    get "/users/", UserController, :index
  end
end

lib/plan_picker_web/controllers/class_management_controller.ex
defmodule PlanPickerWeb.ClassManagementController do
  use PlanPickerWeb, :controller

  def index(conn, %{
        "enrollment_id" => enrollment_id,
        "subject_id" => subject_id,
        "class_id" => class_id
      }) do
    enrollment = PlanPicker.Enrollment.get_enrollment!(enrollment_id)

    selected_subject = PlanPicker.Subject.get_subject!(subject_id)

    selected_class = PlanPicker.Class.get_class!(class_id)

    render(conn, "index.html",
      enrollment: enrollment,
      selected_subject: selected_subject,
      selected_class: selected_class
    )
  end

  def index(conn, %{"enrollment_id" => enrollment_id, "subject_id" => subject_id}) do
    enrollment = PlanPicker.Enrollment.get_enrollment!(enrollment_id)

    selected = PlanPicker.Subject.get_subject!(subject_id)

    render(conn, "index.html",
      enrollment: enrollment,
      selected_subject: selected,
      selected_class: nil
    )
  end

  def index(conn, %{"id" => enrollment_id}) do
    enrollment = PlanPicker.Enrollment.get_enrollment!(enrollment_id)

    case enrollment.subjects do
      [selected | _] ->
        redirect(conn,
          to: Routes.class_management_path(conn, :index, enrollment.id, selected.id)
        )

      _ ->
        render(conn, "index.html",
          enrollment: enrollment,
          selected_subject: nil,
          selected_class: nil
        )
    end
  end
end

lib/plan_picker_web/live/class_management_live.ex
defmodule PlanPickerWeb.ClassManagementLive do
  use PlanPickerWeb, :live_view
  alias PlanPicker.{Accounts, Class, Enrollment, Role, Subject}

  def selected?(nil, _), do: false

  def selected?(selected, el) when is_list(selected),
    do: Enum.any?(selected, &(el.id == &1.id))

  def selected?(selected, el), do: selected.id == el.id

  def get_points(selected_class, points_assignments, user_id) do
    if selected_class == nil do
      ""
    else
      case Map.get(points_assignments, user_id) do
        nil -> "Assigned 0 points"
        num -> ~E"Assigned <%= num %> points"
      end
    end
  end

  def sort_by_points(users, points_assignments) do
    Enum.sort(users, fn a, b ->
      points_assignments[b.id] == nil || points_assignments[a.id] >= points_assignments[b.id]
    end)
  end

  def mount(%{"id" => enrollment_id}, %{"user_token" => token} = _session, socket) do
    enrollment = Enrollment.get_enrollment!(enrollment_id)

    user = Accounts.get_user_by_session_token(token)

    roles = Role.get_roles_for(user)

    socket =
      if user in enrollment.users || :admin in roles do
        subject = get_first_subject(enrollment)

        socket
        |> assign(:enrollment, enrollment)
        |> assign(:selected_subject, subject)
        |> assign(:selected_class, nil)
        |> assign(:selected_users, [])
        |> assign(:points_assignments, %{})
      else
        socket
        |> put_flash(:error, "You do not have required permissions to view this enrollment.")
        |> redirect(to: Routes.enrollment_management_path(socket, :index))
      end

    {:ok, socket}
  end

  def handle_event("toggle_user", %{"id" => user_id}, socket) do
    user = Accounts.get_user!(user_id)

    selected_users = socket.assigns[:selected_users]

    if user in selected_users do
      {:noreply, assign(socket, :selected_users, List.delete(selected_users, user))}
    else
      {:noreply, assign(socket, :selected_users, [user | selected_users])}
    end
  end

  def handle_event("select_subject", %{"id" => subject_id}, socket) do
    case socket.assigns[:selected_subject].id do
      ^subject_id ->
        {:noreply, socket}

      _ ->
        new_subject = Subject.get_subject!(subject_id)
        {:noreply, assign(socket, :selected_subject, new_subject)}
    end
  end

  def handle_event("select_class", %{"id" => class_id}, socket) do
    selected_class = socket.assigns[:selected_class]

    if selected_class do
      case socket.assigns[:selected_class].id do
        ^class_id ->
          {:noreply, socket}

        _ ->
          new_class = Class.get_class!(class_id)

          selected_users =
            Enum.filter(socket.assigns[:selected_users], &(&1 not in new_class.users))

          points_assignments =
            socket.assigns[:enrollment].users
            |> Enum.map(fn user -> {user.id, Class.get_points(new_class, user)} end)
            |> Map.new()

          socket =
            socket
            |> assign(:selected_class, new_class)
            |> assign(:selected_users, selected_users)
            |> assign(:points_assignments, points_assignments)

          {:noreply, socket}
      end
    else
      new_class = Class.get_class!(class_id)

      selected_users = Enum.filter(socket.assigns[:selected_users], &(&1 not in new_class.users))

      points_assignments =
        socket.assigns[:enrollment].users
        |> Enum.map(fn user -> {user.id, Class.get_points(new_class, user)} end)
        |> Map.new()

      socket =
        socket
        |> assign(:selected_class, new_class)
        |> assign(:selected_users, selected_users)
        |> assign(:points_assignments, points_assignments)

      {:noreply, socket}
    end
  end

  def handle_event("add_users_to_class", _opts, socket) do
    new_class =
      Class.assign_users_to_class!(
        socket.assigns[:selected_class],
        socket.assigns[:selected_users]
      )

    subject = socket.assigns[:selected_subject]

    socket =
      socket
      |> assign(:selected_class, new_class)
      |> assign(:selected_users, [])
      |> assign(:selected_subject, Subject.get_subject!(subject.id))

    {:noreply, socket}
  end

  def handle_event("remove_user_from_class", %{"id" => user_id}, socket) do
    user = PlanPicker.Accounts.get_user!(user_id)
    new_class = Class.remove_user_from_class!(socket.assigns[:selected_class], user)

    subject = socket.assigns[:selected_subject]

    socket =
      socket
      |> assign(:selected_class, new_class)
      |> assign(:selected_subject, Subject.get_subject!(subject.id))

    {:noreply, socket}
  end

  defp get_first_subject(enrollment) do
    case enrollment.subjects do
      [subject | _] -> Subject.get_subject!(subject.id)
      nil -> nil
    end
  end
end

lib/plan_picker_web/views/class_management_view.ex
defmodule PlanPickerWeb.ClassManagementView do
  use PlanPickerWeb, :view
end

lib/plan_picker_web/templates/class_management/_user_list.html.eex
<%= if length(@users) > 0 do %>
    <%= for user <- @users do %>
        <div class="block">
            <%= user.index_no %>, <%= user.name %> <%= user.last_name %>
        </div>
<% end %>
<% else %>
    <div class="block">
        <%= @no_users_prompt %>
    </div>
<% end %>

lib/plan_picker_web/templates/class_management/index.html.eex
<h1 class="title"> Classes in <%= @enrollment.name %> </h1>
<%= link "Back to enrollment", to: Routes.enrollment_path(@conn, :show, @enrollment.id) %>

<div class="columns">
    <div class="column is-one-quarter">
        <%= render "_user_list.html", conn: @enrollment, users: @enrollment.users, no_users_prompt: "There are no users assigned to this enrollment." %>
    </div>
    <div class="column">
        <div class="tabs is-toggle is-centered">
            <ul>
                <%= for subject <- @enrollment.subjects do %>
                    <%= if subject.id == @selected_subject.id do %>
                        <li class="is-active"><a> <%= subject.name %> </a></li>
                    <% else %>
                        <li><%= link subject.name, to: Routes.class_management_path(@conn, :index, @enrollment.id, subject.id) %></li>
                    <% end %>
                <% end %>
            </ul>
        </div>

        <%= if length(@selected_subject.classes) > 0 do %>
            <%= if @selected_class != nil do %>
                <div class="box"> <%= render "show.html", conn: @conn, class: @selected_class, selected: true %> </div>
            <% end %>
            <%= for class <- @selected_subject.classes do %>
                <% class_is_selected = @selected_class && @selected_class.id == class.id %>
                <%= if !class_is_selected do %>
                    <%= link to: Routes.class_management_path(@conn, :index, @enrollment.id, @selected_subject.id, class.id), class: :box do %>
                        <%= render "show.html", conn: @conn, class: class, selected: false %>
                    <% end %>
                <% end %>
            <% end %>
        <% else %>
            <div class="block">
                There are no classes of this subject.
            </div>
        <% end %>
    </div>
</div>

lib/plan_picker_web/templates/class_management/show.html.eex
<h2 class="subtitle"> <%= @class.teacher.name %> <%= @class.teacher.surname %> </h2>
<%= for term <- @class.terms do %>
    <p class="content"> <%= term.interval %> </p>
<% end %>
<%= if @selected do %>
    <%= render "_user_list.html", conn: @conn, users: @class.users, no_users_prompt: "There are no users in this group." %>
<% else %>
    <%= length(@class.users) %> users in this group.
<% end %>